pipeline {
    agent any

	tools {
   		  nodejs "node"
   	}

    stages {
        stage('Build FrontEnd') {
        steps {
        		checkout scm

        		sh '''
              cd front-end
              npm install
              npm run build
            '''
        }
           post {
                success {
              	echo "Send slack and email notification"
                archiveArtifacts 'front-end/dist/'
                }
            }
        }
        stage ('Build and Push to Docker') {
            steps {
            sh '''
            mv front-end/Dockerfile Dockerfile
            '''
                script{
                  if (env.BRANCH.contains("release")) {
                        def packageVersion = sh(script: "grep \"version\" front-end/package.json | cut -d '\"' -f4 | tr -d '[[:space:]]'", returnStdout: true)
                        echo "Version is ${packageVersion}"

                        dockerImage = docker.build("tppd2122/frontend")
                        docker.withRegistry( '', 'dockerhub') {
                          dockerImage.push("${packageVersion}")
                          dockerImage.push('latest')
                        }
                    }
                }
            }
        }
    }
}
