pipeline {
    agent any

	tools {
   		  maven "maven"
   	}

    stages {
        stage('Build Infographics') {
        steps {
        		checkout scm

        		sh '''
              cd infographics-service
              mvn -f pom.xml clean package
            '''
        }
           post {
                success {
              	echo "Send slack and email notification"
                //junit '**/target/surefire-reports/TEST-*.xml'
                //archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage ('Build and Push to Docker') {
            steps {
                script{
                if (env.BRANCH.contains("release")) {
                     def packageVersion = "0.0.1"
                     //def packageVersion = sh(script: "mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q", returnStdout: true)
                     //echo "Version is ${packageVersion}"
                    dockerImage = docker.build("tppd2122/infographics", "-f infographics-service/Dockerfile .")
                    docker.withRegistry( '', 'dockerhub') {
                      dockerImage.push("${packageVersion}")
                      dockerImage.push('latest')
                    }
                  }
                }
            }
        }
    }
}
