pipeline {
    agent any
    stages {
        stage('Build webCrawler') {
            steps {
            	checkout scm
                sh '''
            		    cd webcrawler
            		    ./gradlew build
            		'''
            }
             post {
                success {
              	echo "Send slack and email notification"
                //junit '**/target/surefire-reports/TEST-*.xml'
                //archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage ('Build and Push to Docker') {
            steps {
                script{
                    dockerImage = docker.build("tppd2122/webcrawler", '-f webcrawler/Dockerfile .')
                    docker.withRegistry( '', 'dockerhub') {
                      dockerImage.push("0.2.0")
                      dockerImage.push('latest')
                    }
                }
            }
        }
    }
}
