---
- hosts: localhost
  become: true

  vars:
    infographic_host_port: 8080
    infographic_container_port: 8080
    
  vars_files:
    secret.yml

  tasks:
    - name: Stop any container Infographics running
      docker_container:
        name: infographic_pd
        state: absent
    
    - name: Install and run infographics
      shell: docker run -d -p "{{infographic_host_port}}:{{infographic_container_port}}" --name infographic_pd tppd2122/infographics:latest
    
    - name: Notify of pipeline success
      mail:
        host: smtp.gmail.com
        port: 587
        sender: "{{ inventory_hostname }}"
        username: "{{ email_smtp_username }}"
        password: "{{ email_smtp_password }}"
        to: "{{ email_smtp_username }}"
        subject: "Email By Ansible with host {{ inventory_hostname }}"
        body: Test successful
      delegate_to: localhost
        
      
