---
- hosts: localhost
  become: true

  vars:
    host_port: 8081
    container_port: "8080"
    
  vars_files:
    secret.yml

  tasks:
    - name: Stop any container running
      docker_container:
        name: webcrawler_pd
        state: absent
  
    - name: Pull and run WebCrawler image
      command: docker run -d -p "{{host_port}}:{{container_port}}" --name webcrawler_pd tppd2122/webcrawler:latest

    - name: Notify of pipeline success
      mail:
        host: smtp.gmail.com
        port: 587
        sender: "{{ inventory_hostname }}"
        username: "{{ email_smtp_username }}"
        password: "{{ email_smtp_password }}"
        to: "{{ email_smtp_username }}"
        subject: "WebCrawler as run successfully with Ansible with host {{ inventory_hostname }}"
        body: Test successful
      delegate_to: localhost
        
      
